# Generated by Django 3.0.4 on 2020-03-31 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200331_1951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
