# Generated by Django 3.0.4 on 2020-04-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200401_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activate_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
