# Generated by Django 3.0.4 on 2020-03-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=150)),
                ('about_us', models.TextField()),
                ('email', models.CharField(max_length=155)),
                ('phone', models.CharField(max_length=155)),
            ],
        ),
    ]
