# Generated by Django 3.1.3 on 2020-11-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='images/service/')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('icon', models.ImageField(upload_to='images/statistics/')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/team/')),
                ('facebook', models.URLField()),
                ('linkedin', models.URLField()),
                ('website', models.URLField()),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
