# Generated by Django 3.1.3 on 2020-11-18 10:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_auto_20201118_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='about_us',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
