# Generated by Django 3.1.3 on 2020-11-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0006_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='image_main',
            field=models.ImageField(null=True, upload_to='estate/%Y/%m/%d'),
        ),
    ]
