# Generated by Django 3.1.3 on 2020-11-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0007_estate_image_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='plan_1',
            field=models.ImageField(null=True, upload_to='estate/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='video',
            field=models.FileField(null=True, upload_to='estates/videos/%Y/%m/%d'),
        ),
    ]
