# Generated by Django 3.1.3 on 2020-11-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0008_auto_20201118_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='location',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='video',
        ),
        migrations.AddField(
            model_name='estate',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estate',
            name='video_cover',
            field=models.ImageField(blank=True, null=True, upload_to='estate/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='estate',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='plan_1',
            field=models.ImageField(blank=True, null=True, upload_to='estate/%Y/%m/%d'),
        ),
    ]
