# Generated by Django 3.1.3 on 2020-11-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0009_auto_20201118_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
