# Generated by Django 3.1.3 on 2020-11-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0011_nearby_estate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
