# Generated by Django 3.1.3 on 2020-11-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0013_auto_20201118_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='area',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='garages',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='year_built',
        ),
        migrations.AlterField(
            model_name='estate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
