# Generated by Django 3.1.3 on 2020-11-26 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0014_auto_20201126_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.estate'),
        ),
    ]
