# Generated by Django 3.1.3 on 2020-11-26 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0016_review_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.estate'),
        ),
    ]
